### ISSUE TITLE
Remove User/Batch Card: status message and current user/batch. 

### ISSUE THREAD

**Issue by atif-vsbizz** [fakhruddin-vsbizz/arabic-moallema-refactored-v2.0#13]
Backend: @somesh2001 
status msg (warning, error, success) should be appear based on user's action.

Frontend: @AtifSyed07
remove the border on current user/ current batch value.

**Comment by atif-vsbizz** [comment]
[Update]

Backend: @somesh2001 [Open]
status msg (warning, error, success) should be appear based on user's action.

Frontend: @AtifSyed07 [Fixed]
remove the border on current user/ current batch value.

**Comment by fakhruddin-vsbizz** [comment]
Alerts done.

Resolved by @somesh2001.
