### ISSUE TITLE
Add new batch or Edit batch is not working

### ISSUE THREAD

**Issue by atif-vsbizz** [fakhruddin-vsbizz/arabic-moallema-refactored-v2.0#19]
@somesh2001 

Add new batch  or Edit batch is not responding on Teacher Detail Card at: admin/teachers/teacherprofile/

**Comment by somesh2001** [comment]
> @somesh2001
> 
> Add new batch or Edit batch is not responding on Teacher Detail Card at: admin/teachers/teacherprofile/

See add new batch to a teacher is on hold as of now (the functionality part) because the batch already have a teacher when the batch is created, and edit teacher batch is working.
