### ISSUE TITLE
Mark present and absent in teacher chapter detail

### ISSUE THREAD

**Issue by somesh2001** [fakhruddin-vsbizz/arabic-moallema-refactored-v2.0#47]
On the chapter details page, marking the student present and absent is not functional.

path -> http://localhost:3000/teacher/chapter-detail/Letter%20Learning%20Part%202/Batch%203

**Comment by fakhruddin-vsbizz** [comment]
@somesh2001 what is the ask over this issue?

**Comment by somesh2001** [comment]
> @somesh2001 what is the ask over this issue?

In the chapters details when we click on mark present and mark absent, it should be functional. It is not working now!!

**Comment by fakhruddin-vsbizz** [comment]
@atif-vsbizz please remove the checkboxes inside them.

**Comment by atif-vsbizz** [comment]
[Update]

Ui is done

**Comment by fakhruddin-vsbizz** [comment]
[UPDATE]

Functionality out-of-scope. Closing.

**Comment by somesh2001** [comment]
Done
